# 指定Eureka服务地址
eureka:
  instance:
    # 配置心跳
    lease-renewal-interval-in-seconds: 30     # 心跳的间隔
    lease-expiration-duration-in-seconds: 90  # 多久没发生，就认为你宕机了
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
#      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka
    registry-fetch-interval-seconds: 30  # 每隔多久去更新一下本地的注册表信息

# 指定具体服务的负载均衡策略
SEARCH:        # 编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule  # 具体负载均衡使用的类

# 指定服务名称
spring:
  application:
    name: CUSTOMER


