server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    # 当前的Eureka服务是单机版的
#    registerWithEureka: false
#    fetchRegistry: false
    # 下面配置的Eureka是高可用模式
    registerWithEureka: true  # 注册到Eureka上
    fetchRegistry: true       # 从Eureka上拉取信息
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
# 指定spring-security的用户名和密码
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: EUREKA02




